'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Arts',
      [
        {
          gallery_id: 1,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/656/484/large/titas-zenevicius-ssp-keyframe-1-finalv9.jpg?1707899637',
          title: 'Leap of faith',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 2,
          src: 'https://cdnb.artstation.com/p/assets/images/images/072/485/995/4k/chengwei-pan-1.jpg?1707463211',
          title: 'PRESTIGE CYBER HALO JANNA',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 2,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/486/000/4k/chengwei-pan-2.jpg?1707462772',
          title: 'PRESTIGE CYBER HALO JANNA',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 2,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/486/004/4k/chengwei-pan-3.jpg?1707462783',
          title: 'PRESTIGE CYBER HALO JANNA',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 3,
          src: 'https://cdnb.artstation.com/p/assets/images/images/063/976/859/large/sun-haiyang-1.jpg?1686814576',
          title: 'Souvenir',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 3,
          src: 'https://cdnb.artstation.com/p/assets/images/images/063/976/885/large/sun-haiyang-203.jpg?1686814417',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 4,
          src: 'https://cdna.artstation.com/p/assets/images/images/058/168/584/large/bo-chen-mythmaker-irelia-final-1920px.jpg?1673537643',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 4,
          src: 'https://cdnb.artstation.com/p/assets/images/images/058/168/655/large/bo-chen-mythmaker-irelia-sketches-a-d-3k.jpg?1673537323',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 5,
          src: 'https://cdnb.artstation.com/p/assets/images/images/063/271/093/4k/igor-sid-necro.jpg?1685121602',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 6,
          src: 'https://cdnb.artstation.com/p/assets/images/images/068/400/289/large/lejia-chan-coven-splash-akali-02-jia.jpg?1697708853',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 7,
          src: 'https://cdnb.artstation.com/p/assets/images/images/068/752/079/large/-.jpg?1698581209',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 8,
          src: 'https://cdna.artstation.com/p/assets/images/images/057/925/448/large/tadek-wbfs-v01-tadeuszchmiel-still-v01-v3.jpg?1672983646',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 8,
          src: 'https://cdna.artstation.com/p/assets/images/images/057/925/438/large/tadek-wbfs-v01-tadeuszchmiel-still-v01-v0.jpg?1672983618',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 8,
          src: 'https://cdnb.artstation.com/p/assets/images/images/057/925/489/large/tadek-highresscreenshot00002.jpg?1672983775',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 9,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/103/251/large/pianpian-zou-00478-108975552.jpg?1687140594',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 10,
          src: 'https://cdna.artstation.com/p/assets/images/images/063/782/742/large/evan-sisson-highresscreenshot00001.jpg?1686330611',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 11,
          src: 'https://cdna.artstation.com/p/assets/images/images/066/071/808/large/chunxu-liu-0-4.jpg?1691985049',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 12,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/344/724/4k/erik-van-helvoirt-workshop-final.jpg?1678361255',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 13,
          src: 'https://cdna.artstation.com/p/assets/images/images/058/153/236/large/ekaterina-tambovtseva-blue-sails-art-trade-1.jpg?1673504384',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 14,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/482/865/large/sergey-kolesov-lgd-2-stealth-scene-4k-01.jpg?1702629594',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 15,
          src: 'https://cdna.artstation.com/p/assets/images/images/062/601/872/4k/yi-y-2s.jpg?1683544403',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 16,
          src: 'https://cdna.artstation.com/p/assets/images/images/066/201/852/large/sung-choi-space-station-sungchoi-1600px-glazed.jpg?1692297151',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 17,
          src: 'https://cdnb.artstation.com/p/assets/images/images/059/677/529/4k/sin-jong-hun-61-the-dream-of-a-whale.jpg?1676916723',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 18,
          src: 'https://cdna.artstation.com/p/assets/images/images/064/376/626/large/sang-delan-575.jpg?1687793654',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 19,
          src: 'https://cdna.artstation.com/p/assets/images/images/070/582/332/large/sylvain-sarrailh-under-the-pylons.jpg?1702913820',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 20,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/063/296/4k/chris-doretz-chrisdoretz-city-03.jpg?1699277300',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 20,
          src: 'https://cdnb.artstation.com/p/assets/images/images/069/063/293/4k/chris-doretz-chrisdoretz-city-02.jpg?1699277294',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 20,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/063/290/4k/chris-doretz-chrisdoretz-city-01.jpg?1699277287',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 21,
          src: 'https://cdnb.artstation.com/p/assets/images/images/065/268/437/large/antonio-j-manzanedo-elesh-norn-promotional-image-1920x1080-manzanedo.jpg?1689934499',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 22,
          src: 'https://cdna.artstation.com/p/assets/images/images/061/580/476/large/vetarmora-vamp3.jpg?1681158455',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 23,
          src: 'https://cdna.artstation.com/p/assets/images/images/058/436/040/4k/dominik-mayer-taintedgrail-marketingart-approved.jpg?1674148245',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 24,
          src: 'https://cdnb.artstation.com/p/assets/images/images/059/843/855/large/antonio-j-manzanedo-werewolf-manzanedo-5.jpg?1677251565',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 25,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/413/195/large/anato-finnstark-anato-finnstark-anato-finnstark-web-petit-1.jpg?1687875282',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 26,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/062/346/4k/ming-ming-john-2023-11-2.jpg?1699275794',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 27,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/901/236/large/timofey-razumov-cage.jpg?1679564043',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 28,
          src: 'https://cdnb.artstation.com/p/assets/images/images/061/477/901/4k/dominik-mayer-theoldone-01.jpg?1680885259',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 29,
          src: 'https://cdnb.artstation.com/p/assets/images/images/058/366/755/4k/jerx-s-marantz-leon-stage-2-color-opt-4-2-x-copy.jpg?1673993190',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 30,
          src: 'https://cdnb.artstation.com/p/assets/images/images/065/893/099/large/anato-finnstark-web.jpg?1691505377',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 31,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/355/863/large/yohann-schepacz-bigcatroundbrush-28-wip06wb.jpg?1702343124',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 32,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/173/565/large/yohann-schepacz-red-arrows-courrier-designideation-w.jpg?1701910453',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // {
        //   gallery_id: ,
        //   src: '',
        //   title: '',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   gallery_id: ,
        //   src: '',
        //   title: '',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   gallery_id: ,
        //   src: '',
        //   title: '',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Arts', null, {});
  },
};
