'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Arts',
      [
        {
          gallery_id: 1,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/656/484/large/titas-zenevicius-ssp-keyframe-1-finalv9.jpg?1707899637',
          title: 'Leap of faith',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 2,
          src: 'https://cdnb.artstation.com/p/assets/images/images/072/485/995/4k/chengwei-pan-1.jpg?1707463211',
          title: 'PRESTIGE CYBER HALO JANNA',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 2,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/486/000/4k/chengwei-pan-2.jpg?1707462772',
          title: 'PRESTIGE CYBER HALO JANNA',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 2,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/486/004/4k/chengwei-pan-3.jpg?1707462783',
          title: 'PRESTIGE CYBER HALO JANNA',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 3,
          src: 'https://cdnb.artstation.com/p/assets/images/images/063/976/859/large/sun-haiyang-1.jpg?1686814576',
          title: 'Souvenir',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 3,
          src: 'https://cdnb.artstation.com/p/assets/images/images/063/976/885/large/sun-haiyang-203.jpg?1686814417',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 4,
          src: 'https://cdna.artstation.com/p/assets/images/images/058/168/584/large/bo-chen-mythmaker-irelia-final-1920px.jpg?1673537643',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 4,
          src: 'https://cdnb.artstation.com/p/assets/images/images/058/168/655/large/bo-chen-mythmaker-irelia-sketches-a-d-3k.jpg?1673537323',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 5,
          src: 'https://cdnb.artstation.com/p/assets/images/images/063/271/093/4k/igor-sid-necro.jpg?1685121602',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 6,
          src: 'https://cdnb.artstation.com/p/assets/images/images/068/400/289/large/lejia-chan-coven-splash-akali-02-jia.jpg?1697708853',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 7,
          src: 'https://cdnb.artstation.com/p/assets/images/images/068/752/079/large/-.jpg?1698581209',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 8,
          src: 'https://cdna.artstation.com/p/assets/images/images/057/925/448/large/tadek-wbfs-v01-tadeuszchmiel-still-v01-v3.jpg?1672983646',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 8,
          src: 'https://cdna.artstation.com/p/assets/images/images/057/925/438/large/tadek-wbfs-v01-tadeuszchmiel-still-v01-v0.jpg?1672983618',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 8,
          src: 'https://cdnb.artstation.com/p/assets/images/images/057/925/489/large/tadek-highresscreenshot00002.jpg?1672983775',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 9,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/103/251/large/pianpian-zou-00478-108975552.jpg?1687140594',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 10,
          src: 'https://cdna.artstation.com/p/assets/images/images/063/782/742/large/evan-sisson-highresscreenshot00001.jpg?1686330611',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 11,
          src: 'https://cdna.artstation.com/p/assets/images/images/066/071/808/large/chunxu-liu-0-4.jpg?1691985049',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 12,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/344/724/4k/erik-van-helvoirt-workshop-final.jpg?1678361255',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 13,
          src: 'https://cdna.artstation.com/p/assets/images/images/058/153/236/large/ekaterina-tambovtseva-blue-sails-art-trade-1.jpg?1673504384',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 14,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/482/865/large/sergey-kolesov-lgd-2-stealth-scene-4k-01.jpg?1702629594',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 15,
          src: 'https://cdna.artstation.com/p/assets/images/images/062/601/872/4k/yi-y-2s.jpg?1683544403',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 16,
          src: 'https://cdna.artstation.com/p/assets/images/images/066/201/852/large/sung-choi-space-station-sungchoi-1600px-glazed.jpg?1692297151',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 17,
          src: 'https://cdnb.artstation.com/p/assets/images/images/059/677/529/4k/sin-jong-hun-61-the-dream-of-a-whale.jpg?1676916723',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 18,
          src: 'https://cdna.artstation.com/p/assets/images/images/064/376/626/large/sang-delan-575.jpg?1687793654',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 19,
          src: 'https://cdna.artstation.com/p/assets/images/images/070/582/332/large/sylvain-sarrailh-under-the-pylons.jpg?1702913820',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 20,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/063/296/4k/chris-doretz-chrisdoretz-city-03.jpg?1699277300',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 20,
          src: 'https://cdnb.artstation.com/p/assets/images/images/069/063/293/4k/chris-doretz-chrisdoretz-city-02.jpg?1699277294',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 20,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/063/290/4k/chris-doretz-chrisdoretz-city-01.jpg?1699277287',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 21,
          src: 'https://cdnb.artstation.com/p/assets/images/images/065/268/437/large/antonio-j-manzanedo-elesh-norn-promotional-image-1920x1080-manzanedo.jpg?1689934499',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 22,
          src: 'https://cdna.artstation.com/p/assets/images/images/061/580/476/large/vetarmora-vamp3.jpg?1681158455',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 23,
          src: 'https://cdna.artstation.com/p/assets/images/images/058/436/040/4k/dominik-mayer-taintedgrail-marketingart-approved.jpg?1674148245',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 24,
          src: 'https://cdnb.artstation.com/p/assets/images/images/059/843/855/large/antonio-j-manzanedo-werewolf-manzanedo-5.jpg?1677251565',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 25,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/413/195/large/anato-finnstark-anato-finnstark-anato-finnstark-web-petit-1.jpg?1687875282',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 26,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/062/346/4k/ming-ming-john-2023-11-2.jpg?1699275794',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 27,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/901/236/large/timofey-razumov-cage.jpg?1679564043',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 28,
          src: 'https://cdnb.artstation.com/p/assets/images/images/061/477/901/4k/dominik-mayer-theoldone-01.jpg?1680885259',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 29,
          src: 'https://cdnb.artstation.com/p/assets/images/images/058/366/755/4k/jerx-s-marantz-leon-stage-2-color-opt-4-2-x-copy.jpg?1673993190',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 30,
          src: 'https://cdnb.artstation.com/p/assets/images/images/065/893/099/large/anato-finnstark-web.jpg?1691505377',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 31,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/355/863/large/yohann-schepacz-bigcatroundbrush-28-wip06wb.jpg?1702343124',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 31,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/173/565/large/yohann-schepacz-red-arrows-courrier-designideation-w.jpg?1701910453',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 32,
          src: 'https://cdnb.artstation.com/p/assets/images/images/067/019/297/large/jonathan-wesslund-5-shibainu-smaller.jpg?1694359920',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 32,
          src: 'https://cdna.artstation.com/p/assets/images/images/067/019/294/large/jonathan-wesslund-4-australianshepherd-smaller.jpg?1694359912',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 32,
          src: 'https://cdna.artstation.com/p/assets/images/images/067/019/288/large/jonathan-wesslund-3-xoloitzcuintle-smaller.jpg?1694359904',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 32,
          src: 'https://cdnb.artstation.com/p/assets/images/images/067/019/305/large/jonathan-wesslund-8-alaskanmalamute-smaller.jpg?1694359942',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 33,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/495/395/large/envar-studio-nidalee-4.jpg?1688049446',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 33,
          src: 'https://cdna.artstation.com/p/assets/images/images/064/495/454/large/envar-studio-runeterra-nidalee-thumbnail-06.jpg?1688049516',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 34,
          src: 'https://cdna.artstation.com/p/assets/images/images/069/916/264/large/yohann-schepacz-bigcatroundbrush-23-wip05w.jpg?1701306518',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 35,
          src: 'https://cdna.artstation.com/p/assets/images/images/068/672/046/large/yohann-schepacz-bigcatroundbrush-20-wip05cw.jpg?1698365274',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 35,
          src: 'https://cdnb.artstation.com/p/assets/images/images/068/672/055/large/yohann-schepacz-bigcatroundbrush-20-wip07w.jpg?1698365244',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 35,
          src: 'https://cdna.artstation.com/p/assets/images/images/068/672/050/large/yohann-schepacz-bigcatroundbrush-20-wip08w.jpg?1698365229',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 36,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/495/459/large/envar-studio-nidaleecat.jpg?1688049522',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 37,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/343/244/large/a-xiang-1.jpg?1680840181',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 37,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/343/230/large/a-xiang-2.jpg?1678354145',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 38,
          src: 'https://cdnb.artstation.com/p/assets/images/images/060/470/501/large/sergey-gurskiy-fffox1122.jpg?1678650259',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 38,
          src: 'https://cdnb.artstation.com/p/assets/images/images/060/470/091/large/sergey-gurskiy-fffox11.jpg?1678649366',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 39,
          src: 'https://cdna.artstation.com/p/assets/images/images/067/019/512/large/jonathan-wesslund-29-siberianhusky-smaller.jpg?1694360404',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 39,
          src: 'https://cdnb.artstation.com/p/assets/images/images/067/019/497/large/jonathan-wesslund-27-germanshepherd-smaller.jpg?1694360387',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 39,
          src: 'https://cdnb.artstation.com/p/assets/images/images/067/019/487/large/jonathan-wesslund-25-pembrokewelshcorgi-smaller.jpg?1694360359',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 40,
          src: 'https://cdnb.artstation.com/p/assets/images/images/058/995/183/4k/luis-nieves-arnold20l.jpg?1675386608',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 40,
          src: 'https://cdnb.artstation.com/p/assets/images/images/048/983/605/4k/luis-nieves-arnold-green.jpg?1651424128',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 41,
          src: 'https://cdnb.artstation.com/p/assets/images/images/064/450/587/large/sefki-ibrahim-cine01.jpg?1687955488',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 42,
          src: 'https://cdna.artstation.com/p/assets/images/images/067/669/602/large/blu1304-rey-046.jpg?1695918421',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 43,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/143/156/4k/kev-li-colorcorrect-jpg.jpg?1677910578',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 43,
          src: 'https://cdna.artstation.com/p/assets/images/images/060/140/790/4k/kev-li-greywf-4k-8bit.jpg?1677901149',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 44,
          src: 'https://cdna.artstation.com/p/assets/images/images/067/619/084/4k/fabio-cazzador-149.jpg?1695805697',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 45,
          src: 'https://cdna.artstation.com/p/assets/images/images/068/095/676/4k/ivailo-ivanov-1.jpg?1696971146',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 46,
          src: 'https://cdna.artstation.com/p/assets/images/images/068/095/676/4k/ivailo-ivanov-1.jpg?1696971146',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 46,
          src: 'https://cdnb.artstation.com/p/assets/images/images/068/058/665/4k/ivailo-ivanov-3.jpg?1696893425',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 47,
          src: 'https://cdna.artstation.com/p/assets/images/images/064/591/266/4k/christian-boro-pufftank-main-01.jpg?1688305443',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 47,
          src: 'https://cdna.artstation.com/p/assets/images/images/064/591/298/4k/christian-boro-pufftank-tracks-back-01.jpg?1688305412',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 48,
          src: 'https://cdnb.artstation.com/p/assets/images/images/072/699/325/large/michal-kus-light-tank-next-generation.jpg?1707996520',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 49,
          src: 'https://cdnb.artstation.com/p/assets/images/images/072/635/543/large/michal-kus-ahd-week8-abrams-fotobash-copy.jpg?1707846383',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 49,
          src: 'https://cdnb.artstation.com/p/assets/images/images/072/635/537/large/michal-kus-ahd-week1-abrams-studyy-color.jpg?1707846320',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 50,
          src: 'https://cdnb.artstation.com/p/assets/images/images/072/294/753/large/tritonist-titan-1.jpg?1707056982',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 50,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/294/758/large/tritonist-titan-2.jpg?1707056993',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 50,
          src: 'https://cdna.artstation.com/p/assets/images/images/072/294/770/large/tritonist-titan-4.jpg?1707057015',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 51,
          src: 'https://cdnb.artstation.com/p/assets/images/images/070/597/869/4k/fei-hu-fei-dredd-bike-r4-r5.jpg?1702949100',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 51,
          src: 'https://cdna.artstation.com/p/assets/images/images/070/597/880/4k/fei-hu-fei-dredd-bike-g1-r6.jpg?1702949118',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 51,
          src: 'https://cdna.artstation.com/p/assets/images/images/070/597/878/4k/fei-hu-fei-dredd-bike-g2-r5.jpg?1702949111',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 52,
          src: 'https://cdnb.artstation.com/p/assets/images/images/071/270/339/large/stanis_lav-dorodnev-p-1.jpg?1704825976',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          gallery_id: 52,
          src: 'https://cdnb.artstation.com/p/assets/images/images/071/270/397/large/stanis_lav-dorodnev-r-26.jpg?1704824518',
          title: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // {
        //   gallery_id: 53,
        //   src: 'https://cdna.artstation.com/p/assets/images/images/072/004/312/large/mikhail-sachko-1.jpg?1706435578',
        //   title: '',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   gallery_id: 54,
        //   src: 'https://cdnb.artstation.com/p/assets/images/images/072/004/315/large/mikhail-sachko-2.jpg?1706433742',
        //   title: '',
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Arts', null, {});
  },
};
