'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Posts',
      [
        {
          user_id: 2,
          category_id: 1,
          title: 'Leap of faith',
          description:
            'The air thickened as the device powered up, its engines roaring and distorting the space around them. Amidst the chaos, faint shouts from the general barely pierced through the noise, although they were unintelligible. All of a sudden, everything went quiet...',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 1,
          title: 'PRESTIGE CYBER HALO JANNA',
          description: `Hello everyone, It's been quite some time since my last update. I've been deeply immersed in managing my studio and navigating through various life events. Despite the hustle, it feels incredibly rewarding to finally have a moment to sit down and dedicate myself to painting, especially for all my wonderful students. I hope each of you is having a fantastic Lunar New Year 2024!`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 1,
          title: 'Souvenir',
          description: 'character design for a previous project（2022-2023）',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 1,
          title: 'Mythmaker Irelia splash',
          description: `It is my honor to paint Irelia splash again, This is a Lunar new year skin. Irelia recognizes her full potential, entering back to the Myth paper world and bringing festival joy with her`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 1,
          title: 'Diablo IV Necromancer Key Art',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 1,
          title: 'Coven Akali',
          description: 'Splash from LEAGUE OF LEGENDS by RIOT GAMES',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 2,
          title: '硫原子',
          description:
            '个人独自完成的想法，目前还是很不完善，喜欢日后可以弥补更多不足',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 2,
          title: 'The Celestial Pantheon | Unreal Engine 5 | Epic Fellowship',
          description:
            'I recently completed the Epic Games World Building Fellowship, which was a 3.5-week intensive course focusing on building',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 2,
          title: '欧式建筑6-19',
          description: 'ai细画',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 2,
          title: 'Percolating Abhorrents Portal',
          description: `This scene depicts some sort of machine to study the portal that the Percolating Abhorrent emerges being operated by the protagonist of my hobby game. The first scene I've built in Unreal Engine 5, it has been very intuitive to work with especially the lighting. The character was built in reallusion's character creator but I am hoping to swap him out for a metahuman character soon.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 2,
          title: '圣白教堂',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'The Machinist',
          description: `Another new image! For this one I really wanted to push my 3d skills. For the environment I downloaded a several assets from Sketchfab and a bunch of them I made by myself using blender and substance painter. The character is made with Character Creator and is dressed with Marvelous Designer, I used blenders new hair system for the hair.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'New pet',
          description: 'an artwork I made for a friend <3',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'Blade announcement visuals',
          description: `Three visuals I've done to support the announcement of the Marvel BLADE videogame from Arkane studios Lyon.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'Malenia',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'Space station',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'Whale journey',
          description: `Hello, everyone!!
          It's been a while since I did my solo work...
          I've been busy with other schedules for a while
          I'll work hard to show you a better picture in the future~
          I look forward to your kind cooperation..!
          So far, there have been various works about whales. I tried my own color once..! haha`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: '童话骑士',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 3,
          title: 'Under the pylons',
          description: 'Just a few more minutes before the end of the weekend.',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'Purge I',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'Elesh Norn',
          description:
            'A piece of promotional art I did for Magic The Gathering - Phyrexia: All Will Be One.',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'vamp_h',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'King Arthur - Tainted Grail',
          description: `An epic painting I did last year for AwakenRealms!
          It is a dark version of the King Arthur saga for their game Tainted Grail: The Fall of Avalon.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'Werewolf',
          description: `Hey there, here's a new personal piece.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'The Nine',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'Killer Nun',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'cage.',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'The Old One',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'LEON BOSS DESIGN: The Callisto Protocol',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 4,
          title: 'So much work...',
          description: `Support my work here and get all my burshes pack, timelapes and a lot of HD wallpaper :
          "Death, exhausted by its burden to bear, strives in silence..."`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'BCRB 8 - RED ARROWS',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'Doggust 2023 - Part 1',
          description:
            'First batch of dog paintings I did during August for a challenge called Doggust. A lot of fun but very stressful, I did go some days over time but still happy I managed to make all of them smiling_face',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'Nidalee',
          description:
            'We are mega hyped to share the update on Nidalee for Runeterra, our team had so much fun with this!',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'BIG CAT ROUND BRUSH 7',
          description:
            '"Big Cat Round Brush" Series - Hard Round Brush Sketches 23 done for my IP "CAT EMPIRE : ODONATA"',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'BIG CAT ROUND BRUSH 6',
          description:
            '"Big Cat Round Brush" Series - HRB Sketches 22 done for our IP "Cat Empire : Odonata" Been posting these on Instagram first',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'Nidalee Cat',
          description:
            'We are mega hyped to share the update on Nidalee for Runeterra, our team had so much fun',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'Dragon Tirannosaurs',
          description: 'based on awesome fanArt by Nicola Saviori',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'Foxsamurai',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 5,
          title: 'Doggust 2023 - Part 2',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 6,
          title: 'Baria Sūtsu',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 6,
          title: 'PEDRO PASCAL "JOEL" (UE5)',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 6,
          title: 'Rey Skywalker',
          description:
            'I had a pleasure to texture, lookdev and groom this amazing model by Kubisi art.',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 6,
          title: 'Joyeeta - Holi Festival',
          description:
            'This work was inspired by the model Joyeeta Sanyal from one of her photo sets during the Holi Festival',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 6,
          title: 'Harpy of the North - Cardinal Winds',
          description: `Hi everyone!
          This is my reinterpretation of one of the harpies from the stunning artwork "Cardinal Winds`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 6,
          title: 'Oi !',
          description: `Realtime Rendered in Unreal Engine 5
          This was inspired by some renders from the Callisto Protocol here on Artstation and also Karl Urban's awesome portrayal of Billy Butcher`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'Puff Tank',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'Next Gen MBT - Concept',
          description: `Concept done to test out a workflow I do not employ too much. Photobashing results in quick realistic concepts but it does have its limitations in terms of design. I always like to render on top of it to unify the shape flow, consistency of details and the overall design philisophy.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'Steroid Abrams',
          description: `Started as a demo for our students at Focal Point School. Showing and explaining students how to employ fotos and mix in your own render styl into it to unify a concept . This design is a heavily upgraded M1 Abrams tank! Featuring modular composite armored skirts on the Sides. Improved optics. New High velocity machine gun for light targets. Amongst many other features.`,
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'Warlord-class Titan',
          description:
            'The project presents a 33 meter long Warlord-class Titan from the Warhammer 40000 universe.',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'Dredd 02 - Pursuit Bike',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'Soviet tanks object 780',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          user_id: 2,
          category_id: 7,
          title: 'BMW M3 G80 Widebody',
          description: '',
          isModerated: true,
          isAdult: false,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    Example: await queryInterface.bulkDelete('Posts', null, {});
  },
};
